


run: compile error1 error1x error2 error2x error3 error3x arrays arraysx conditionals condtionalsx recursion recursionx iteration iterationx functions functionsx dictionary dictionaryx problem problemx


arrays: compile
	cat srcCodesNes/ArrayTest.nes

arraysx: compile
	java -classpath classfiles nntndohrs.NntndoHRs srcCodesNes/ArrayTest.nes

error1:

error1x:

error2:

error2x:

error3:

error3x:

conditionals:

condtionalsx:

recursion:

recursionx:

iteration:

iterationx:

functions:

functionsx:

dictionary:

dictionaryx:

problem:

problemx:

compile: 
	javac -d classfiles -sourcepath src src/nntndohrs/NntndoHRs.java

clean:
	rm -f classfiles/nntndohrs/*.class



